# Este é um arquivo de configuração
# aqui devemos descrever e definir as 
# gatilhos, etapas, versões e comandos
# que essa máquina/robô deve executar

# Nome do nosso teste
name: Python application test

# Definimos quando essa ação deve ser executada. Aqui estamos usando "push"
# que significa que a ação será executada sempre que um push for feito ao repositório.
on: 
  push:
    branches:
      - main # Pode ser qualquer branch que você deseja monitorar

# Definimos os trabalhos (jobs) que queremos executar
jobs: 
  build: # Nome do trabalho, pode ser qualquer coisa significativa para o contexto

    runs-on: ubuntu-latest # Plataforma onde a ação será executada

    steps: 
    - name: Checkout repository # Primeiro passo: fazer o checkout do repositório
      uses: actions/checkout@v2 # Ação para fazer o checkout do código-fonte

    - name: Setup Python version # Configurar a versão do Python
      uses: actions/setup-python@v2 # Ação para configurar o Python
      with:
        python-version: '3.8' # Escolha a versão do Python que deseja usar

    - name: Install dependencies # Instalar dependências do projeto
      run: |
        python -m pip install --upgrade pip # Atualizar o pip
        pip install -r requirements.txt # Instalar dependências listadas no arquivo requirements.txt

    - name: Run tests # Executar os testes
      run: python -m unittest discover -s . # Comando para descobrir e rodar testes com o unittest
